name: Dart

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        sdk: [stable]
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            output: linux-bin
          - os: macOS-latest
            output: mac-bin
          - os: windows-latest
            output: windows-bin.exe
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Build
        run: mkdir build && dart compile exe bin/main.dart -o ./build/${{ matrix.output }}

      - uses: actions/upload-artifact@v1
        with:
          name: dart-native-executables
          path: build
